stages:
  - build
  - pages

build:
  stage: build
  image: python
  script:
    - pip install pre-commit
    - pre-commit run -a --hook-stage=manual
    - ./build
  artifacts:
    paths:
      - public

pages:
  stage: pages
  script: ls -lah public/
  only:
  - master
  artifacts:
    paths:
      - public
