[book]
authors = ["Stavros Korokithakis"]
language = "en"
multilingual = false
src = "content"
title = "Stavros' Notes"

[output.html]
curly-quotes = true
no-section-label = true
git-repository-url = "https://gitlab.com/stavros/notes/"
git-repository-icon = "fa-gitlab"
additional-css = ["static/custom.css"]

[preprocessor.linkify]
command = "python3 scripts/mdbook-linkify.py"
renderers = ["html"]
after = ["links"]
