[book]
authors = ["Stavros Korokithakis"]
language = "en"
src = "content"
title = "Stavros' Notes"

[output.html]
smart-punctuation = true
no-section-label = true
preferred-dark-theme = "coal"
git-repository-url = "https://gitlab.com/stavros/notes/"
git-repository-icon = "fab-gitlab"
additional-css = ["static/custom.css"]

[preprocessor.linkify]
command = "python3 scripts/mdbook-linkify.py"
renderers = ["html"]
after = ["links"]
